sudo: required
dist: trusty
addons:
  artifacts:
    paths:
      - results
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - '7'
cache:
  directories:
    - node_modules
    - bower_components
    - $HOME/.npm
    - $HOME/.cache
before_script:
  - npm install
before_deploy:
  - npm run build
env:
  global:
    - NODE_ENV=testing
    - ARTIFACTS_BUCKET=js-tasks-ru
    - secure: >-
        eRG+sHh81sN4YxGJEMFpXiz4XPvotwOILai+67tv8p0mDwSQeKOtCO4VBmCe2G+uLQmf2Sub/HefHOT433lKbcozCdxBOMyKzFXk6dFFnnrMY4drcvhRXQrH6vKFGR0gaAylI3X6Grsiw4v7Ykw4e+7UjnNHuMH5PdCjx790pqu+lwCipkgpuCOrPLFRKEmqx+FeHWa+I+/j2tfHzPlu1W5neQ1OcN6nZ9s7vzJMHs/WvEZZcXeDci0ZJwuVex8ntSDc+L03vmPsyPFsEtY4EnfFezGmwV3vQQJj9/nNPhbd6UjlO+ZygWoxOgwyj4ylhooQ/1rc44G301iczIdbRJ+6Viqm8e1qAUdlftXFijkiRUvyVUiMC247mrcxrIU3Yi2v8QvhmypBLiWniQ0v7SjHd8YG4rK9jgy/a9oqsDlRS5HDkTP3MWJvgtkEUjiEACniEm7tvp9WbNm9HXG1M69PABsyLoDFOookWg/Z057q+MyTW3GWS8hJKQfXtC5pHOKG9Xj/KFm2qhGI3DJxdoo4V9NgVckwzUKQnF0Bh5JOjazWAuQvPkjNOJJkGZtlaTZItemgtymOt1lmpR1r2NECo0OX4SNoSg0LMwjZg4dXTptwXlQF8FqdMXm5X1EDDEDav7Q0QQTQvQ5ax2zIj5Qjq4hATRi6p1xfCxADxwM=
    - secure: >-
        MBYiSYmWPh63YquiQUcfZkCT6Cm3uimlGEWTL1uaf0HgsFwqmcM7VaVOTd8OqpoVT+MGcyhNiZsxAvgaKvGq6F//U0PWBZgKVJL0cqXtxgdL19ARAqPzX8LQhbnB1ALOQjlF7hzCDcugjN03Ec9NKyHjCZeYPrAuSaIQKrXYLfHHH/jrVlRYJ7JWDQnHPtIymF8lN5rSuG4scjtBa2Gqy9mq8+tIm9vDyKc2pTB+XuyUnlpg7JkDuwKEdXykVjGtAwR+RUXV3GLXkLAijRKnWyVChc+nvffb/eDV2epqZ5FB5z9if0KSsGhjLc2y5VakQtmgpWGci8gnf7D7TA+3jQR9j+Tqsy8sZIga1OPAR00sCF3jUfZHz/7MGEnBn0Bs1XPuT40LGgcvIZPM+ZtvwuYJX4q52vKaR9E0lVt6+NIIdMz3/Gq1Zp4Ipuh5CvsHY4QRY2umH36v6HN/wD8aJ+amZjRfJSyxCfiXYC4U4vipYb6vy1pk/BR4Pf8kbdigMvqLPWnT6TAtZmtD983k8yxdnBuUDWvALRszCWvAWazrnyOGETFD5aoWmW4nN5fxMw4cxdl9NagdUPmdXHm/EMShzBfTW3LUmOuOL7w4sCLlrTCiNr9OAlBPAsX/ylIJZZYZqNW5+PwPbY4AXN+hQbeTtJO03ovASrswtyo61Ns=
script:
  - npm run test
notifications:
  webhooks: 'http://learn.javascript.ru/automation/ci/build'
